spring.datasource.url=jdbc:mysql://mysqldb:3306/tbcpl_workforce_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=tbcpl_user
spring.datasource.password=tbcpl_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.tbcpl.workforce=DEBUG
app.base-url=http://localhost:5173
